name: "pnpm"
description: "Set up pnpm and install dependencies"

inputs:
  pnpm-version:
    description: 'pnpm version'
    required: false
    default: 9.4.0
  node-version:
    description: 'Node.js version'
    required: false
    default: 20.17.0 # Default to the latest 20 LTS version

runs:
  using: "composite"
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"

    - name: Install dependencies
      shell: bash
      run: pnpm install